title: "Hamzauddin Siddiqui - Data Analyst Portfolio"
description: "Data Analyst specializing in Operations Research, Business Analytics, and Supply Chain optimization. Currently based in Germany."
url: "https://hamzauddin-siddiqui.github.io"
baseurl: ""

# Personal information
author:
  name: "Hamzauddin Siddiqui"
  email: "hamzauddin54@gmail.com"
  linkedin: "https://www.linkedin.com/in/hamzauddin-siddiqui-786180175"
  github: "https://github.com/Hamzauddin-Siddiqui"
  location: "Magdeburg, Germany"

# SEO and social
lang: en_US
timezone: Europe/Berlin

# Build settings for GitHub Pages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation menu
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Custom navigation labels
navigation:
  - title: "Home"
    url: "/"
  - title: "About" 
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

# Social media (for theme)
github_username: Hamzauddin-Siddiqui
linkedin_username: hamzauddin-siddiqui-786180175

# Google Analytics (optional - you can add this later)
# google_analytics: "G-XXXXXXXXXX"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
# Theme settings
minima:
  skin: auto
