# Site settings
title: ""
email: hamzauddin54@gmail.com
description: ""
baseurl: ""
url: "https://hamzauddin-siddiqui.github.io"

# Social media and contact
github_username: Hamzauddin-Siddiqui
linkedin_username: hamzauddin-siddiqui-786180175

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Minima theme customization
minima:
  skin: auto

# Disable default header pages to prevent double navigation
header_pages: []

# Remove all other social links
twitter_username: ""
author: ""
