# Site settings
title: ""
email: hamzauddin54@gmail.com
description: ""
baseurl: ""
url: "https://hamzauddin-siddiqui.github.io"

# Social media and contact
github_username: Hamzauddin-Siddiqui
linkedin_username: hamzauddin-siddiqui-786180175

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Minima theme customization
minima:
  skin: auto

# Navigation
header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md

# Footer settings (empty to minimize footer content)
author: ""
twitter_username: ""
github_username: ""
